
//delphi°æ±¾
//{$IFDEF VER80}  - Delphi 1
//{$IFDEF VER90}  - Delphi 2
//{$IFDEF VER100} - Delphi 3
//{$IFDEF VER120} - Delphi 4
//{$IFDEF VER130} - Delphi 5
//{$IFDEF VER140} - Delphi 6
//{$IFDEF VER150} - Delphi 7
//{$IFDEF VER160} - Delphi 8
//{$IFDEF VER170} - Delphi 2005
//{$IFDEF VER180} - Delphi 2006
//{$IFDEF VER180} - Delphi 2007
//{$IFDEF VER185} - Delphi 2007
//{$IFDEF VER200} - Delphi 2009
//{$IFDEF VER210} - Delphi 2010
//{$IFDEF VER220} - Delphi XE

//±àÒëÆ÷°æ±¾(CompilerVersion)
//Delphi XE   - 22
//Delphi 2010 - 21
//Delphi 2009 - 20
//Delphi 2007 - 18.5
//Delphi 2006 - 18
//Delphi 2005 - 17
//Delphi 8    - 16
//Delphi 7    - 15
//Delphi 6    - 14


{$IF CompilerVersion >= 18.5}
 {$define D2007UP}
{$IFEND}